/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LosslessGovernanceInterface extends ethers.utils.Interface {
  functions: {
    "COMMITEE_INDEX()": FunctionFragment;
    "COMMITTEE_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "HUNDRED()": FunctionFragment;
    "LSS_TEAM_INDEX()": FunctionFragment;
    "TOKEN_OWNER_INDEX()": FunctionFragment;
    "addCommitteeMembers(address[])": FunctionFragment;
    "claimCommitteeReward(uint256)": FunctionFragment;
    "committeeMemberVote(uint256,bool)": FunctionFragment;
    "committeeMembersCount()": FunctionFragment;
    "compensationPercentage()": FunctionFragment;
    "extaordinaryRetrieval(address[],address)": FunctionFragment;
    "getAmountReported(uint256)": FunctionFragment;
    "getIsVoted(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getVersion()": FunctionFragment;
    "getVote(uint256,uint256)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address,address,address,uint256)": FunctionFragment;
    "isCommitteeMember(address)": FunctionFragment;
    "isReportActive(uint256)": FunctionFragment;
    "isReportSolved(uint256)": FunctionFragment;
    "losslessClaim(uint256)": FunctionFragment;
    "losslessController()": FunctionFragment;
    "losslessReporting()": FunctionFragment;
    "losslessStaking()": FunctionFragment;
    "losslessVote(uint256,bool)": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "proposeWallet(uint256,address)": FunctionFragment;
    "proposedWalletOnReport(uint256)": FunctionFragment;
    "rejectWallet(uint256)": FunctionFragment;
    "removeCommitteeMembers(address[])": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "reportResolution(uint256)": FunctionFragment;
    "reportVotes(uint256)": FunctionFragment;
    "resolveReport(uint256)": FunctionFragment;
    "retrieveCompensation()": FunctionFragment;
    "retrieveFunds(uint256)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setCompensationAmount(uint256)": FunctionFragment;
    "setDisputePeriod(uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tokenOwnersVote(uint256,bool)": FunctionFragment;
    "unpause()": FunctionFragment;
    "walletDisputePeriod()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "COMMITEE_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COMMITTEE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "HUNDRED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LSS_TEAM_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_OWNER_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCommitteeMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCommitteeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeMemberVote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeMembersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "compensationPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extaordinaryRetrieval",
    values: [string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountReported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIsVoted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCommitteeMember",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isReportActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReportSolved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "losslessClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "losslessController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "losslessReporting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "losslessStaking",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "losslessVote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeWallet",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposedWalletOnReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectWallet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCommitteeMembers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "reportResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveCompensation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompensationAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOwnersVote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "walletDisputePeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COMMITEE_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COMMITTEE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "HUNDRED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LSS_TEAM_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_OWNER_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCommitteeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCommitteeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeMemberVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeMembersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compensationPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extaordinaryRetrieval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountReported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIsVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCommitteeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReportActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReportSolved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "losslessClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "losslessController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "losslessReporting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "losslessStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "losslessVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposedWalletOnReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCommitteeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveCompensation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCompensationAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOwnersVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletDisputePeriod",
    data: BytesLike
  ): Result;

  events: {
    "CommitteeMajorityReach(uint256,bool)": EventFragment;
    "CommitteeMemberClaim(uint256,address,uint256)": EventFragment;
    "CommitteeMemberNegativeVote(uint256,address)": EventFragment;
    "CommitteeMemberPositiveVote(uint256,address)": EventFragment;
    "CommitteeMembersRemoval(address[])": EventFragment;
    "CompensationRetrieval(address,uint256)": EventFragment;
    "ExtraordinaryProposalAccept(address)": EventFragment;
    "FundsRetrieval(uint256,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "LosslessClaim(address,uint256,uint256)": EventFragment;
    "LosslessTeamNegativeVote(uint256)": EventFragment;
    "LosslessTeamPositiveVote(uint256)": EventFragment;
    "NewCommitteeMembers(address[])": EventFragment;
    "NewDisputePeriod(uint256)": EventFragment;
    "Paused(address)": EventFragment;
    "ReportResolve(uint256,bool)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TokenOwnersNegativeVote(uint256)": EventFragment;
    "TokenOwnersPositiveVote(uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "WalletProposal(uint256,address)": EventFragment;
    "WalletRejection(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CommitteeMajorityReach"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommitteeMemberClaim"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CommitteeMemberNegativeVote"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CommitteeMemberPositiveVote"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommitteeMembersRemoval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CompensationRetrieval"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ExtraordinaryProposalAccept"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundsRetrieval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LosslessClaim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LosslessTeamNegativeVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LosslessTeamPositiveVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCommitteeMembers"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewDisputePeriod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReportResolve"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenOwnersNegativeVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenOwnersPositiveVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WalletProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WalletRejection"): EventFragment;
}

export type CommitteeMajorityReachEvent = TypedEvent<
  [BigNumber, boolean] & { _reportId: BigNumber; _result: boolean }
>;

export type CommitteeMemberClaimEvent = TypedEvent<
  [BigNumber, string, BigNumber] & {
    _reportId: BigNumber;
    _member: string;
    _amount: BigNumber;
  }
>;

export type CommitteeMemberNegativeVoteEvent = TypedEvent<
  [BigNumber, string] & { _reportId: BigNumber; _member: string }
>;

export type CommitteeMemberPositiveVoteEvent = TypedEvent<
  [BigNumber, string] & { _reportId: BigNumber; _member: string }
>;

export type CommitteeMembersRemovalEvent = TypedEvent<
  [string[]] & { _members: string[] }
>;

export type CompensationRetrievalEvent = TypedEvent<
  [string, BigNumber] & { _wallet: string; _amount: BigNumber }
>;

export type ExtraordinaryProposalAcceptEvent = TypedEvent<
  [string] & { _token: string }
>;

export type FundsRetrievalEvent = TypedEvent<
  [BigNumber, BigNumber] & { _reportId: BigNumber; _amount: BigNumber }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type LosslessClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    _token: string;
    _reportID: BigNumber;
    _amount: BigNumber;
  }
>;

export type LosslessTeamNegativeVoteEvent = TypedEvent<
  [BigNumber] & { _reportId: BigNumber }
>;

export type LosslessTeamPositiveVoteEvent = TypedEvent<
  [BigNumber] & { _reportId: BigNumber }
>;

export type NewCommitteeMembersEvent = TypedEvent<
  [string[]] & { _members: string[] }
>;

export type NewDisputePeriodEvent = TypedEvent<
  [BigNumber] & { _newPeriod: BigNumber }
>;

export type PausedEvent = TypedEvent<[string] & { account: string }>;

export type ReportResolveEvent = TypedEvent<
  [BigNumber, boolean] & { _reportId: BigNumber; _resolution: boolean }
>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string] & {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type TokenOwnersNegativeVoteEvent = TypedEvent<
  [BigNumber] & { _reportId: BigNumber }
>;

export type TokenOwnersPositiveVoteEvent = TypedEvent<
  [BigNumber] & { _reportId: BigNumber }
>;

export type UnpausedEvent = TypedEvent<[string] & { account: string }>;

export type WalletProposalEvent = TypedEvent<
  [BigNumber, string] & { _reportId: BigNumber; _wallet: string }
>;

export type WalletRejectionEvent = TypedEvent<
  [BigNumber] & { _reportId: BigNumber }
>;

export class LosslessGovernance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LosslessGovernanceInterface;

  functions: {
    COMMITEE_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    COMMITTEE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    HUNDRED(overrides?: CallOverrides): Promise<[BigNumber]>;

    LSS_TEAM_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    TOKEN_OWNER_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    addCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimCommitteeReward(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    committeeMemberVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    committeeMembersCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    compensationPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    extaordinaryRetrieval(
      _address: string[],
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAmountReported(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getIsVoted(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVote(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _losslessReporting: string,
      _losslessController: string,
      _losslessStaking: string,
      _walletDisputePeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isCommitteeMember(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isReportActive(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isReportSolved(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    losslessClaim(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    losslessController(overrides?: CallOverrides): Promise<[string]>;

    losslessReporting(overrides?: CallOverrides): Promise<[string]>;

    losslessStaking(overrides?: CallOverrides): Promise<[string]>;

    losslessVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    proposeWallet(
      _reportId: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposedWalletOnReport(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        BigNumber,
        BigNumber,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        proposal: number;
        committeeDisagree: number;
        retrievalAmount: BigNumber;
        timestamp: BigNumber;
        wallet: string;
        status: boolean;
        losslessVote: boolean;
        losslessVoted: boolean;
        tokenOwnersVote: boolean;
        tokenOwnersVoted: boolean;
        walletAccepted: boolean;
      }
    >;

    rejectWallet(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reportResolution(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    reportVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, boolean, BigNumber] & {
        resolved: boolean;
        resolution: boolean;
        losslessPayed: boolean;
        amountReported: BigNumber;
      }
    >;

    resolveReport(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retrieveCompensation(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    retrieveFunds(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCompensationAmount(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDisputePeriod(
      _timeFrame: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tokenOwnersVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    walletDisputePeriod(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  COMMITEE_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  COMMITTEE_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  HUNDRED(overrides?: CallOverrides): Promise<BigNumber>;

  LSS_TEAM_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  TOKEN_OWNER_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  addCommitteeMembers(
    _members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimCommitteeReward(
    _reportId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  committeeMemberVote(
    _reportId: BigNumberish,
    _vote: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  committeeMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

  compensationPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  extaordinaryRetrieval(
    _address: string[],
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAmountReported(
    _reportId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getIsVoted(
    _reportId: BigNumberish,
    _voterIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getVersion(overrides?: CallOverrides): Promise<BigNumber>;

  getVote(
    _reportId: BigNumberish,
    _voterIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _losslessReporting: string,
    _losslessController: string,
    _losslessStaking: string,
    _walletDisputePeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isCommitteeMember(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isReportActive(
    _reportId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isReportSolved(
    _reportId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  losslessClaim(
    _reportId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  losslessController(overrides?: CallOverrides): Promise<string>;

  losslessReporting(overrides?: CallOverrides): Promise<string>;

  losslessStaking(overrides?: CallOverrides): Promise<string>;

  losslessVote(
    _reportId: BigNumberish,
    _vote: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  proposeWallet(
    _reportId: BigNumberish,
    _wallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposedWalletOnReport(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      BigNumber,
      BigNumber,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean
    ] & {
      proposal: number;
      committeeDisagree: number;
      retrievalAmount: BigNumber;
      timestamp: BigNumber;
      wallet: string;
      status: boolean;
      losslessVote: boolean;
      losslessVoted: boolean;
      tokenOwnersVote: boolean;
      tokenOwnersVoted: boolean;
      walletAccepted: boolean;
    }
  >;

  rejectWallet(
    _reportId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeCommitteeMembers(
    _members: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reportResolution(
    _reportId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  reportVotes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [boolean, boolean, boolean, BigNumber] & {
      resolved: boolean;
      resolution: boolean;
      losslessPayed: boolean;
      amountReported: BigNumber;
    }
  >;

  resolveReport(
    _reportId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retrieveCompensation(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  retrieveFunds(
    _reportId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCompensationAmount(
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDisputePeriod(
    _timeFrame: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokenOwnersVote(
    _reportId: BigNumberish,
    _vote: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  walletDisputePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    COMMITEE_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    COMMITTEE_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    HUNDRED(overrides?: CallOverrides): Promise<BigNumber>;

    LSS_TEAM_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_OWNER_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitteeMembers(
      _members: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimCommitteeReward(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    committeeMemberVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    committeeMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

    compensationPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    extaordinaryRetrieval(
      _address: string[],
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getAmountReported(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIsVoted(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    getVote(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _losslessReporting: string,
      _losslessController: string,
      _losslessStaking: string,
      _walletDisputePeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    isCommitteeMember(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isReportActive(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isReportSolved(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    losslessClaim(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    losslessController(overrides?: CallOverrides): Promise<string>;

    losslessReporting(overrides?: CallOverrides): Promise<string>;

    losslessStaking(overrides?: CallOverrides): Promise<string>;

    losslessVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    proposeWallet(
      _reportId: BigNumberish,
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    proposedWalletOnReport(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        BigNumber,
        BigNumber,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        proposal: number;
        committeeDisagree: number;
        retrievalAmount: BigNumber;
        timestamp: BigNumber;
        wallet: string;
        status: boolean;
        losslessVote: boolean;
        losslessVoted: boolean;
        tokenOwnersVote: boolean;
        tokenOwnersVoted: boolean;
        walletAccepted: boolean;
      }
    >;

    rejectWallet(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    removeCommitteeMembers(
      _members: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    reportResolution(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    reportVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, boolean, BigNumber] & {
        resolved: boolean;
        resolution: boolean;
        losslessPayed: boolean;
        amountReported: BigNumber;
      }
    >;

    resolveReport(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    retrieveCompensation(overrides?: CallOverrides): Promise<void>;

    retrieveFunds(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCompensationAmount(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDisputePeriod(
      _timeFrame: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokenOwnersVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    walletDisputePeriod(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CommitteeMajorityReach(uint256,bool)"(
      _reportId?: BigNumberish | null,
      _result?: boolean | null
    ): TypedEventFilter<
      [BigNumber, boolean],
      { _reportId: BigNumber; _result: boolean }
    >;

    CommitteeMajorityReach(
      _reportId?: BigNumberish | null,
      _result?: boolean | null
    ): TypedEventFilter<
      [BigNumber, boolean],
      { _reportId: BigNumber; _result: boolean }
    >;

    "CommitteeMemberClaim(uint256,address,uint256)"(
      _reportId?: BigNumberish | null,
      _member?: string | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { _reportId: BigNumber; _member: string; _amount: BigNumber }
    >;

    CommitteeMemberClaim(
      _reportId?: BigNumberish | null,
      _member?: string | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, string, BigNumber],
      { _reportId: BigNumber; _member: string; _amount: BigNumber }
    >;

    "CommitteeMemberNegativeVote(uint256,address)"(
      _reportId?: BigNumberish | null,
      _member?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _member: string }
    >;

    CommitteeMemberNegativeVote(
      _reportId?: BigNumberish | null,
      _member?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _member: string }
    >;

    "CommitteeMemberPositiveVote(uint256,address)"(
      _reportId?: BigNumberish | null,
      _member?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _member: string }
    >;

    CommitteeMemberPositiveVote(
      _reportId?: BigNumberish | null,
      _member?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _member: string }
    >;

    "CommitteeMembersRemoval(address[])"(
      _members?: null
    ): TypedEventFilter<[string[]], { _members: string[] }>;

    CommitteeMembersRemoval(
      _members?: null
    ): TypedEventFilter<[string[]], { _members: string[] }>;

    "CompensationRetrieval(address,uint256)"(
      _wallet?: string | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { _wallet: string; _amount: BigNumber }
    >;

    CompensationRetrieval(
      _wallet?: string | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { _wallet: string; _amount: BigNumber }
    >;

    "ExtraordinaryProposalAccept(address)"(
      _token?: string | null
    ): TypedEventFilter<[string], { _token: string }>;

    ExtraordinaryProposalAccept(
      _token?: string | null
    ): TypedEventFilter<[string], { _token: string }>;

    "FundsRetrieval(uint256,uint256)"(
      _reportId?: BigNumberish | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _reportId: BigNumber; _amount: BigNumber }
    >;

    FundsRetrieval(
      _reportId?: BigNumberish | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { _reportId: BigNumber; _amount: BigNumber }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "LosslessClaim(address,uint256,uint256)"(
      _token?: string | null,
      _reportID?: BigNumberish | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { _token: string; _reportID: BigNumber; _amount: BigNumber }
    >;

    LosslessClaim(
      _token?: string | null,
      _reportID?: BigNumberish | null,
      _amount?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { _token: string; _reportID: BigNumber; _amount: BigNumber }
    >;

    "LosslessTeamNegativeVote(uint256)"(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    LosslessTeamNegativeVote(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    "LosslessTeamPositiveVote(uint256)"(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    LosslessTeamPositiveVote(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    "NewCommitteeMembers(address[])"(
      _members?: null
    ): TypedEventFilter<[string[]], { _members: string[] }>;

    NewCommitteeMembers(
      _members?: null
    ): TypedEventFilter<[string[]], { _members: string[] }>;

    "NewDisputePeriod(uint256)"(
      _newPeriod?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _newPeriod: BigNumber }>;

    NewDisputePeriod(
      _newPeriod?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _newPeriod: BigNumber }>;

    "Paused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Paused(account?: null): TypedEventFilter<[string], { account: string }>;

    "ReportResolve(uint256,bool)"(
      _reportId?: BigNumberish | null,
      _resolution?: boolean | null
    ): TypedEventFilter<
      [BigNumber, boolean],
      { _reportId: BigNumber; _resolution: boolean }
    >;

    ReportResolve(
      _reportId?: BigNumberish | null,
      _resolution?: boolean | null
    ): TypedEventFilter<
      [BigNumber, boolean],
      { _reportId: BigNumber; _resolution: boolean }
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "TokenOwnersNegativeVote(uint256)"(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    TokenOwnersNegativeVote(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    "TokenOwnersPositiveVote(uint256)"(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    TokenOwnersPositiveVote(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    "Unpaused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Unpaused(account?: null): TypedEventFilter<[string], { account: string }>;

    "WalletProposal(uint256,address)"(
      _reportId?: BigNumberish | null,
      _wallet?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _wallet: string }
    >;

    WalletProposal(
      _reportId?: BigNumberish | null,
      _wallet?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { _reportId: BigNumber; _wallet: string }
    >;

    "WalletRejection(uint256)"(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;

    WalletRejection(
      _reportId?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _reportId: BigNumber }>;
  };

  estimateGas: {
    COMMITEE_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    COMMITTEE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    HUNDRED(overrides?: CallOverrides): Promise<BigNumber>;

    LSS_TEAM_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_OWNER_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimCommitteeReward(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    committeeMemberVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    committeeMembersCount(overrides?: CallOverrides): Promise<BigNumber>;

    compensationPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    extaordinaryRetrieval(
      _address: string[],
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAmountReported(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIsVoted(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    getVote(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _losslessReporting: string,
      _losslessController: string,
      _losslessStaking: string,
      _walletDisputePeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isCommitteeMember(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isReportActive(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isReportSolved(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    losslessClaim(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    losslessController(overrides?: CallOverrides): Promise<BigNumber>;

    losslessReporting(overrides?: CallOverrides): Promise<BigNumber>;

    losslessStaking(overrides?: CallOverrides): Promise<BigNumber>;

    losslessVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    proposeWallet(
      _reportId: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposedWalletOnReport(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rejectWallet(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reportResolution(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reportVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    resolveReport(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retrieveCompensation(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    retrieveFunds(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCompensationAmount(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDisputePeriod(
      _timeFrame: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOwnersVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    walletDisputePeriod(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    COMMITEE_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    COMMITTEE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    HUNDRED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LSS_TEAM_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKEN_OWNER_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimCommitteeReward(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    committeeMemberVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    committeeMembersCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    compensationPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    extaordinaryRetrieval(
      _address: string[],
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAmountReported(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIsVoted(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVote(
      _reportId: BigNumberish,
      _voterIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _losslessReporting: string,
      _losslessController: string,
      _losslessStaking: string,
      _walletDisputePeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isCommitteeMember(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isReportActive(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isReportSolved(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    losslessClaim(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    losslessController(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    losslessReporting(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    losslessStaking(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    losslessVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposeWallet(
      _reportId: BigNumberish,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposedWalletOnReport(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rejectWallet(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeCommitteeMembers(
      _members: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reportResolution(
      _reportId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reportVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resolveReport(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retrieveCompensation(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    retrieveFunds(
      _reportId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCompensationAmount(
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDisputePeriod(
      _timeFrame: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOwnersVote(
      _reportId: BigNumberish,
      _vote: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    walletDisputePeriod(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
